blank_issues_enabled: true
contact_links:
  - name: Our code of conduct
    url: https://github.com/shibatch/nofreelunch
    about: If you have any comments or objections to the CoC, please post your thoughts on this page.
